---
title: "Data Hell<br>on the Catwalk"
subtitle: >
    Um desfile de horrores cotidianos que caem no colo 
    <br>
    de quem importa dados quando menos se espera
    <br>
    *ou*
    <br>
    Ah, qualé! Não é possível que isso pode acontecer!!!
author: Marcelo Ventura Freire
# date: 2026-??-??
lang: pt-br
format: 
  revealjs: 
    # ### formato 1920x1080
    # width: 1920
    # height: 1080
    ### formato 1600x900
    width: 1600
    height: 900
    #
    theme: blood
    slide-level: 3
    slide-number: 
      c/t
      # true
      # h/v
    show-slide-number: speaker
    transition: 
      none
      # zoom
    # smaller: true   # a tentação é grande
    chalkboard: true
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
```

# Roadmap desta apresentação

## Roadmap desta apresentação

- 1^o^ dia: [Aqui](data-hell-on-byte.html)
  - Codificação do dado textual (*encoding*)
  - Armazenamento do dado em memória/disco
- 2^o^ dia: [Aqui](data-hell-on-format.html)
  - Estrutura do arquivo
  - Corrupção de dados 
- 3^o^ dia: Esta apresentação
  - Um desfile de moda dos demônios dos sete círculos do inferno na passarela da
    importação de dados


# O Desfile do Inferno

## Uma breve coletânea de como pode dar merda

\ \ 

Este é uma esboço de uma coleção de vários problemas que acontecem na hora da
importação de dados

\ \ 

Ele não exaure o tema

\ \ 

Deixei de fora erros detectáveis na *crítica* dos dados

::: notes
- Esta é uma pequena coletana de problemas com os quais você pode se deparar ao
  tentar importar um arquivo e receber uma mensagem de erro
- Não tenho a mais mínima intenção de fazer uma cobertura completa do assunto,
  já que a quantidade de formas de acertar é finita (e geralmente bem pequena),
  mas a quantidade de formas que pode dar merda é infinita (e talvez não 
  enumerável)
- Não fazem parte desta coletânea erros de crítica de dados, como inconsistência
  nos dados, inconsistência relacional, formatação, domínio, integridade etc.
:::



# Organizando a bagunça

## Organizando a bagunça

Problemas:

1. Formato e Estrutura das linhas
2. Caracteres Especiais e Parsing
3. Conversão de Tipo
4. Missings/Valores Válidos
5. Formatos de arquivos



# Formato e Estrutura das linhas

## Formato e Estrutura das linhas

1. Codificação de Caracteres
2. Aspas
3. Escapes
4. Quebras de Linha
5. Formato do Arquivo



# Problemas de Caracteres Especiais e Parsing

## Problemas de Caracteres Especiais e Parsing

1. Caracteres que Quebram o Parsing
2. Caracteres de Controle e Não-Printable
3. Caracteres Unicode e Internacionalização



# Problemas de Conversão de Tipo

## Problemas de Conversão de Tipo

Problemas com:

1. Falhas de Conversão Básica
1. Falhas de Conversão por Formato
1. Perda de Precisão na Conversão
1. Formatação de Datas
1. Formatação de Timestamp



# Problemas de Missings/Valores Válidos

## Problemas de Missings/Valores Válidos

1. Representação de Missing
2. Colunas/Registros Vazios



# Formatos de Arquivos

## Formatos de Arquivos

1. FWF
1. DSV
1. YAML
2. JSON
3. XML



