---
title: Levantamento das "aulas" que já postei no grupo
format: 
  html
execute: 
  cache: true
  echo: fenced
---

```{r}
#| label: setup

library(tidyverse)
library(jsonlite)
```
# importação

importando banco de mensagens bruto

```{r}
#| label: importa

if (file.exists("data/msgs-bruto.rds")) {
  msgs.bruto <- read_rds("data/msgs-bruto.rds")
} else {
  message("importando de novo")
  system.time(
    msgs.bruto <- 
      "data/ChatExport_2026-05-13_JSON/msgs-compact.json" |> 
      read_json(
        simplifyVector = TRUE
      ) |> 
      pluck("messages")
  )
  msgs.bruto |> 
    write_rds("data/msgs-bruto.rds", compress = "gz")
}
```


# montando

estudando a estrutura presente

```{r}
#| label: vendo-estrutura

msgs.bruto |> 
  count(type)
msgs.bruto |> 
  count(action) |> 
  arrange(desc(n))
msgs.bruto |> 
  count(actor_id)
msgs.bruto |> 
  count(type, action)
msgs.bruto |> 
  filter(type == "service") |> 
  count(action, actor_id) |> 
  filter(n == 1) |> 
  count(action)
msgs.bruto |> 
  filter(
    type == "service"
    , action %notin% c("invite_members", "join_group_by_link")
  ) |> 
  count(action, actor_id) |> 
  arrange(desc(n))
```

```{r}
#| label: monta-dic-nomes

dic_nomes <- 
  bind_rows(
    msgs.bruto |> 
      select(actor, actor_id) |> 
      filter(!is.na(actor)) |> 
      distinct() |> 
      rename(nome = actor, id = actor_id),
    msgs.bruto |> 
      select(from, from_id) |> 
      filter(!is.na(from)) |> 
      distinct() |> 
      rename(nome = from, id = from_id)
  ) |> 
  distinct() |> 
  mutate(
    id = 
      id |> 
      str_remove("user") |> 
      as.integer()
  ) |> 
  arrange(id)
```


```{r}
#| label: minhas-msgs

msgs.bruto |> 
  filter(
    type == "message"
    , from == "Marcelo Ventura"
  ) |> 
  select(
    !c(
      type, date_unixtime, actor, actor_id, action, title, from, from_id, photo,
      photo_file_size, width, height, file, thumbnail, thumbnail_file_size,
      message_id, via_bot, edited, edited_unixtime, place_name, address,
      location_information, inviter, contact_information, contact_vcard,
      contact_vcard_file_size
    )
  ) |> 
  summary()

minhas.msgs <- 
  msgs.bruto |> 
  filter(
    type == "message"
    , from == "Marcelo Ventura"
  ) |> 
  select(
    !c(
      type, date_unixtime, actor, actor_id, action, title, from, from_id, photo,
      photo_file_size, width, height, file, thumbnail, thumbnail_file_size,
      message_id, via_bot, edited, edited_unixtime, place_name, address,
      location_information, inviter, contact_information, contact_vcard,
      contact_vcard_file_size
    )
  )

# write_rds(minhas.msgs, "data/minhas-msgs.rds")
```

vamos descobrir como extrair o texto das mensagens

```{r}
#| label: tenta-extrair-texto

minhas.msgs$text |> 
  map(length) |> 
  unlist()

minhas.msgs |> 
  filter(map(text, length) > 2) |> 
  summary()

textos <- 
  minhas.msgs |> 
  filter(map(text, length) > 2) |> 
  arrange(desc(map(text, length)))

textos$date[4]

```

preciso ter pelo menos:


```
- msg
  - id
  - type
  - date
  - cont
- author
  - login
  - name
  - id
- text
  - raw
  - entities
- reply.to
  - msg.id
- media
  - type
  - size
- reactions
  [
    - actor
      - login
      - name
      - id
    - reaction
  ]
- citations: <a href="https://t.me/AlbersonMiranda">Alberson</a>
  [
    - actor.name
    - actor.id
  ]
- links
  [
    - url
  ]
- chunks: `<pre> código </pre>`
  [
    - code
  ]
    - ??? n era p existir alguma classe em `<pre>`, tipo `<pre lang="R">`???
```







# manuseio

selecionando as mensagens que postei

```{r}
#| label: filtra-minhas-msgs

minhas.msgs <- 
  msgs.bruto |> 
  filter(from == "Marcelo Ventura")
```

verificando se puxei tudo

```{r}
minhas.msgs |> 
  nrow()
(meu.id <- minhas.msgs |> head(1) |> pluck("from_id"))
msgs.bruto |> 
  filter(from_id == meu.id) |> 
  nrow()
```


uma msg que eu postei

```{r}
msgs.bruto |> 
  filter(id == 198276) |> 
  print()
```

colapsando as mensagens que são continuação

```{r}
msgs.colapsadas <- 
  minhas.msgs |> 
  mutate(
    grupo =
      (1 - continuação) |> 
      cumsum(),
    .before = everything()
  ) |> 
  summarise(
    texto = 
      str_c(texto, collapse = "\n\n"),
    ids =
      str_c(min(id), max(id), sep = ":"),
    início = min(data),
    fim = max(data)
      
  )
```



# pegando as maiores


